### ISSUE TITLE
Document CLI UI guidelines

### ISSUE THREAD

**Issue by cppforlife** [vmware-archive/design-docs#2]
Flag guidelines:
- `--dangerous-*`
- `--*-alpha`

Examples of current inconsistencies:

- running `kapp` produces help msg and error
  - vendir and imgpkg on the other hand just produce error message with list of sub commands
  - ytt and kbld return successfully (since they have root commands registered)

**Comment by aaronshurley** [comment]
Closing this issue in favor of https://github.com/vmware-tanzu/carvel/issues/19.
